ersion: "3.7"
services:
  db:
      image: mysql:latest
      container_name: mysql18_server
      environment:
         MYSQL_ROOT_PASSWORD: "123456"
      expose:
         - 3306
      volumes:
         - /share/mysql_server:/var/lib/mysql
      networks:
        customnetwork:
          ipv4_address: 172.10.0.9
  webserver:
      image: nginx:latest
      container_name: webserver
      volumes:
        - /share/nginx/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      depends_on:
        - web
      networks:
        customnetwork:
          ipv4_address: 172.10.0.8
  web:
      image: pyflasktest:2
      container_name: python311_env
      volumes:
        - /share/pyflask/:/home/pyflask/
      expose:
        - 5000
      depends_on:
        - db
      networks:
        customnetwork:
          ipv4_address: 172.10.0.10
      links:
        - db:db
      working_dir: /home/pyflask
      command: ./wait-for-it.sh db:3306 --timeout=10 --strict -- uwsgi --ini app.ini

networks:
  customnetwork:
    ipam:
      config:
        - subnet : 172.10.0.0/16